name: CI Pipeline

on:
  push:
    branches:
      - main   # This means the workflow will run when you push code to the "main" branch.
  pull_request:
    branches:
      - main   # This makes the workflow run when a pull request is created targeting the "main" branch.

jobs:
  build:
    runs-on: ubuntu-latest  # This means the workflow will run on an Ubuntu server.

    steps:
      - name: Checkout code
        uses: actions/checkout@v2   # This will get the latest version of your code.

      - name: Set up .NET SDK
        uses: actions/setup-dotnet@v1  # This will set up the .NET SDK to build the project.
        with:
          dotnet-version: '7.0'  # This specifies the version of .NET SDK to use.

      - name: Restore dependencies
        run: dotnet restore  # This will restore the project dependencies (get all the libraries you need).

      - name: Build the project
        run: dotnet build  # This will build your C# project.

      - name: Run tests
        run: dotnet test  # This will run your tests to check if everything is working fine.
